"""
backend/notifier.py
===================
Unified notification dispatch system for Traffic Sentinel AI.
Handles automated E-Challan notifications via:
  - Email (SMTP with HTML templates and image attachments)
  - SMS (pluggable gateway: Demo, Twilio, Fast2SMS)

Includes delivery tracking, batch dispatch, and notification log.
"""

import os
import json
import datetime
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage

from backend.sms_gateway import create_sms_gateway


class ChallanNotifier:
    """
    Handles automated digital E-Challan notification dispatch
    via Email (SMTP/HTML with attached evidence ticket) and SMS notification gateway.
    """
    def __init__(self, config=None):
        config = config or {}
        email_cfg = config.get("notifications", {}).get("email", {})
        self.enabled = email_cfg.get("enabled", False)
        self.smtp_server = email_cfg.get("smtp_server", "smtp.gmail.com")
        self.smtp_port = email_cfg.get("smtp_port", 587)
        self.sender_email = email_cfg.get("sender_email", "sentinel-alerts@traffic-sentinel.ai")
        self.sender_password = email_cfg.get("sender_password", "")
        self.sent_log = []

    def send_email_challan(self, recipient_email, owner_name, plate_number, challan_id, fine_amount, challan_image_path=None):
        """
        Sends HTML E-Challan notification email with ticket image attachment.
        Falls back gracefully to mock logging if SMTP credentials are not configured.
        """
        subject = f"🚨 Official Traffic Violation E-Challan Issued — {plate_number} (Challan #{challan_id})"
        body_html = f"""
        <html>
        <body style="font-family: Arial, sans-serif; color: #333; line-height: 1.6;">
            <div style="background-color: #0f172a; padding: 20px; color: #fff; border-radius: 8px 8px 0 0;">
                <h2 style="color: #ef4444; margin: 0;">🚔 Traffic Sentinel AI — Digital E-Challan Notice</h2>
            </div>
            <div style="padding: 20px; border: 1px solid #e2e8f0; border-radius: 0 0 8px 8px;">
                <p>Dear <strong>{owner_name}</strong>,</p>
                <p>An automated traffic violation notice has been generated for your registered vehicle <strong>{plate_number}</strong>.</p>
                <table style="width: 100%; border-collapse: collapse; margin: 15px 0;">
                    <tr><td style="padding: 8px; border-bottom: 1px solid #cbd5e1;"><strong>Challan ID:</strong></td><td style="padding: 8px; border-bottom: 1px solid #cbd5e1;">#{challan_id}</td></tr>
                    <tr><td style="padding: 8px; border-bottom: 1px solid #cbd5e1;"><strong>Vehicle Number:</strong></td><td style="padding: 8px; border-bottom: 1px solid #cbd5e1;">{plate_number}</td></tr>
                    <tr><td style="padding: 8px; border-bottom: 1px solid #cbd5e1;"><strong>Offense:</strong></td><td style="padding: 8px; border-bottom: 1px solid #cbd5e1; color: #dc2626;"><strong>Riding Without Helmet (Sec 129 MVA)</strong></td></tr>
                    <tr><td style="padding: 8px; border-bottom: 1px solid #cbd5e1;"><strong>Penalty Fine:</strong></td><td style="padding: 8px; border-bottom: 1px solid #cbd5e1; color: #16a34a; font-weight: bold;">₹{fine_amount}</td></tr>
                </table>
                <p>Please pay your penalty within 15 days to avoid court summons.</p>
                <p style="font-size: 0.9em; color: #64748b;">This is an automated notification generated by Traffic Sentinel AI Surveillance Network.</p>
            </div>
        </body>
        </html>
        """

        msg_record = {
            "type": "EMAIL",
            "recipient": recipient_email,
            "plate": plate_number,
            "challan_id": challan_id,
            "fine": fine_amount,
            "status": "SENT",
            "timestamp": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        }

        if self.enabled and self.sender_password:
            try:
                msg = MIMEMultipart()
                msg["From"] = self.sender_email
                msg["To"] = recipient_email
                msg["Subject"] = subject
                msg.attach(MIMEText(body_html, "html"))

                if challan_image_path and os.path.exists(challan_image_path):
                    with open(challan_image_path, "rb") as f:
                        img_data = f.read()
                    image_mime = MIMEImage(img_data, name=os.path.basename(challan_image_path))
                    msg.attach(image_mime)

                with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                    server.starttls()
                    server.login(self.sender_email, self.sender_password)
                    server.send_message(msg)
                print(f"[Notifier] Email successfully sent to {recipient_email}")
            except Exception as e:
                print(f"[Notifier] Email send failed ({e}). Mock log recorded.")
                msg_record["status"] = f"MOCK_SENT ({e})"
        else:
            msg_record["status"] = "MOCK_SENT"
            print(f"[Notifier] Mock Email recorded for {recipient_email} (Challan #{challan_id})")

        self.sent_log.append(msg_record)
        return msg_record

    def send_sms_challan(self, phone_number, plate_number, challan_id, fine_amount):
        """Sends an SMS alert notification payload."""
        message = (
            f"Traffic Sentinel Alert: E-Challan #{challan_id} issued for vehicle {plate_number}. "
            f"Fine Amount: INR {fine_amount}. Pay online at https://echallan.parivahan.gov.in"
        )
        msg_record = {
            "type": "SMS",
            "recipient": phone_number,
            "plate": plate_number,
            "challan_id": challan_id,
            "message": message,
            "status": "MOCK_SENT",
            "timestamp": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        }
        self.sent_log.append(msg_record)
        print(f"[Notifier] SMS notification dispatched to {phone_number}: {message}")
        return msg_record


class NotificationCenter:
    """
    Unified notification center combining Email and SMS dispatch
    with delivery tracking, batch operations, and notification history.
    """

    def __init__(self, config=None):
        self.config = config or {}
        self.email_notifier = ChallanNotifier(config)

        sms_cfg = self.config.get("notifications", {}).get("sms", {})
        self.sms_gateway = create_sms_gateway(sms_cfg)

        self.notification_log = []
        self.log_file = self.config.get("notifications", {}).get(
            "log_file", "violations/notification_log.json"
        )
        self._load_log()

    def _load_log(self):
        """Loads existing notification log from disk."""
        try:
            if os.path.exists(self.log_file):
                with open(self.log_file, "r", encoding="utf-8") as f:
                    self.notification_log = json.load(f)
        except Exception:
            self.notification_log = []

    def _save_log(self):
        """Persists notification log to disk."""
        try:
            os.makedirs(os.path.dirname(self.log_file) or ".", exist_ok=True)
            with open(self.log_file, "w", encoding="utf-8") as f:
                json.dump(self.notification_log, f, indent=2, ensure_ascii=False)
        except Exception as e:
            print(f"[NotificationCenter] Log save error: {e}")

    def dispatch_challan_notice(self, violation_record, channels=None):
        """
        Dispatches E-Challan notice via specified channels (email, sms, or both).

        Args:
            violation_record (dict): Violation record with plate_text, owner_name, etc.
            channels (list): List of channels to use. Default: ["email", "sms"].

        Returns:
            dict: Dispatch result with status for each channel.
        """
        channels = channels or ["email", "sms"]
        plate = violation_record.get("plate_text", "UNKNOWN")
        owner = violation_record.get("owner_name", "Vehicle Owner")
        v_id = violation_record.get("violation_id", "N/A")
        fine = float(violation_record.get("challan_amount", 1000.0))
        challan_path = violation_record.get("challan_path", "")

        result = {
            "violation_id": v_id,
            "plate": plate,
            "channels": {},
            "timestamp": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "overall_status": "DISPATCHED"
        }

        if "email" in channels:
            email_addr = f"{plate.lower()}@owner-contact.in"
            email_result = self.email_notifier.send_email_challan(
                recipient_email=email_addr,
                owner_name=owner,
                plate_number=plate,
                challan_id=v_id,
                fine_amount=fine,
                challan_image_path=challan_path
            )
            result["channels"]["email"] = {
                "recipient": email_addr,
                "status": email_result.get("status", "UNKNOWN")
            }

        if "sms" in channels:
            # Generate a demo phone number from plate hash
            phone_hash = abs(hash(plate)) % 9000000000 + 1000000000
            phone = f"+91{phone_hash}"
            sms_message = (
                f"Traffic Sentinel: E-Challan #{v_id} issued for {plate}. "
                f"Fine: INR {fine:.0f}. Pay at echallan.parivahan.gov.in"
            )
            sms_result = self.sms_gateway.send(
                phone_number=phone,
                message=sms_message,
                metadata={"challan_id": v_id, "plate": plate}
            )
            result["channels"]["sms"] = {
                "recipient": phone,
                "status": sms_result.get("status", "UNKNOWN")
            }

        self.notification_log.append(result)
        self._save_log()
        return result

    def dispatch_bulk_notices(self, violation_records, channels=None):
        """
        Dispatches notices for multiple violations.

        Args:
            violation_records (list[dict]): List of violation records.
            channels (list): Channels to dispatch on.

        Returns:
            dict: Summary with total sent, failed, and per-record results.
        """
        results = []
        sent_count = 0
        failed_count = 0

        for record in violation_records:
            try:
                res = self.dispatch_challan_notice(record, channels)
                results.append(res)
                sent_count += 1
            except Exception as e:
                print(f"[NotificationCenter] Bulk dispatch error for {record.get('plate_text')}: {e}")
                failed_count += 1
                results.append({
                    "violation_id": record.get("violation_id", "?"),
                    "overall_status": f"FAILED ({e})"
                })

        return {
            "total_dispatched": sent_count,
            "total_failed": failed_count,
            "results": results
        }

    def get_notification_history(self):
        """Returns the full notification dispatch history."""
        return self.notification_log

    def get_stats(self):
        """Returns notification statistics."""
        total = len(self.notification_log)
        email_count = sum(1 for n in self.notification_log if "email" in n.get("channels", {}))
        sms_count = sum(1 for n in self.notification_log if "sms" in n.get("channels", {}))
        return {
            "total_dispatched": total,
            "email_sent": email_count,
            "sms_sent": sms_count
        }
