import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage

class ChallanNotifier:
    """
    Handles automated digital E-Challan notification dispatch
    via Email (SMTP/HTML with attached evidence ticket) and SMS notification gateway.
    """
    def __init__(self, config=None):
        config = config or {}
        email_cfg = config.get("notifications", {}).get("email", {})
        self.enabled = email_cfg.get("enabled", False)
        self.smtp_server = email_cfg.get("smtp_server", "smtp.gmail.com")
        self.smtp_port = email_cfg.get("smtp_port", 587)
        self.sender_email = email_cfg.get("sender_email", "sentinel-alerts@traffic- sentinel.ai")
        self.sender_password = email_cfg.get("sender_password", "")
        self.sent_log = []

    def send_email_challan(self, recipient_email, owner_name, plate_number, challan_id, fine_amount, challan_image_path=None):
        """
        Sends HTML E-Challan notification email with ticket image attachment.
        Falls back gracefully to mock logging if SMTP credentials are not configured.
        """
        subject = f"🚨 Official Traffic Violation E-Challan Issued — {plate_number} (Challan #{challan_id})"
        body_html = f"""
        <html>
        <body style="font-family: Arial, sans-serif; color: #333; line-height: 1.6;">
            <div style="background-color: #0f172a; padding: 20px; color: #fff; border-radius: 8px 8px 0 0;">
                <h2 style="color: #ef4444; margin: 0;">🚔 Traffic Sentinel AI — Digital E-Challan Notice</h2>
            </div>
            <div style="padding: 20px; border: 1px solid #e2e8f0; border-radius: 0 0 8px 8px;">
                <p>Dear <strong>{owner_name}</strong>,</p>
                <p>An automated traffic violation notice has been generated for your registered vehicle <strong>{plate_number}</strong>.</p>
                <table style="width: 100%; border-collapse: collapse; margin: 15px 0;">
                    <tr><td style="padding: 8px; border-bottom: 1px solid #cbd5e1;"><strong>Challan ID:</strong></td><td style="padding: 8px; border-bottom: 1px solid #cbd5e1;">#{challan_id}</td></tr>
                    <tr><td style="padding: 8px; border-bottom: 1px solid #cbd5e1;"><strong>Vehicle Number:</strong></td><td style="padding: 8px; border-bottom: 1px solid #cbd5e1;">{plate_number}</td></tr>
                    <tr><td style="padding: 8px; border-bottom: 1px solid #cbd5e1;"><strong>Offense:</strong></td><td style="padding: 8px; border-bottom: 1px solid #cbd5e1; color: #dc2626;"><strong>Riding Without Helmet (Sec 129 MVA)</strong></td></tr>
                    <tr><td style="padding: 8px; border-bottom: 1px solid #cbd5e1;"><strong>Penalty Fine:</strong></td><td style="padding: 8px; border-bottom: 1px solid #cbd5e1; color: #16a34a; font-weight: bold;">₹{fine_amount}</td></tr>
                </table>
                <p>Please pay your penalty within 15 days to avoid court summons.</p>
                <p style="font-size: 0.9em; color: #64748b;">This is an automated notification generated by Traffic Sentinel AI Surveillance Network.</p>
            </div>
        </body>
        </html>
        """

        msg_record = {
            "type": "EMAIL",
            "recipient": recipient_email,
            "plate": plate_number,
            "challan_id": challan_id,
            "fine": fine_amount,
            "status": "SENT"
        }

        if self.enabled and self.sender_password:
            try:
                msg = MIMEMultipart()
                msg["From"] = self.sender_email
                msg["To"] = recipient_email
                msg["Subject"] = subject
                msg.attach(MIMEText(body_html, "html"))

                if challan_image_path and os.path.exists(challan_image_path):
                    with open(challan_image_path, "rb") as f:
                        img_data = f.read()
                    image_mime = MIMEImage(img_data, name=os.path.basename(challan_image_path))
                    msg.attach(image_mime)

                with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                    server.starttls()
                    server.login(self.sender_email, self.sender_password)
                    server.send_message(msg)
                print(f"[Notifier] Email successfully sent to {recipient_email}")
            except Exception as e:
                print(f"[Notifier] Email send failed ({e}). Mock log recorded.")
                msg_record["status"] = f"MOCK_SENT ({e})"
        else:
            msg_record["status"] = "MOCK_SENT"
            print(f"[Notifier] Mock Email recorded for {recipient_email} (Challan #{challan_id})")

        self.sent_log.append(msg_record)
        return msg_record

    def send_sms_challan(self, phone_number, plate_number, challan_id, fine_amount):
        """Sends an SMS alert notification payload."""
        message = (
            f"Traffic Sentinel Alert: E-Challan #{challan_id} issued for vehicle {plate_number}. "
            f"Fine Amount: INR {fine_amount}. Pay online at https://echallan.parivahan.gov.in"
        )
        msg_record = {
            "type": "SMS",
            "recipient": phone_number,
            "plate": plate_number,
            "challan_id": challan_id,
            "message": message,
            "status": "MOCK_SENT"
        }
        self.sent_log.append(msg_record)
        print(f"[Notifier] SMS notification dispatched to {phone_number}: {message}")
        return msg_record
